packages:
  - playground
  - docs
  - packages/*
  - examples/*
  - apps/*

ignoreWorkspaceRootCheck: true
shellEmulator: true

catalog:
  '@tailwindcss/vite': ^4.0.6
  '@tanstack/eslint-config': ^0.3.0
  '@tanstack/react-devtools': ^0.7.0
  '@tanstack/react-router': ^1.132.0
  '@tanstack/react-router-devtools': ^1.132.0
  '@tanstack/react-router-ssr-query': ^1.131.7
  '@tanstack/react-start': ^1.132.0
  '@tanstack/router-plugin': ^1.132.0
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.2.0
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@vitejs/plugin-react': ^5.0.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  jsdom: ^27.0.0
  lucide-react: ^0.544.0
  prettier: ^3.5.3
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwind-merge: ^3.0.2
  tailwindcss: ^4.0.6
  tw-animate-css: ^1.3.6
  vite-tsconfig-paths: ^5.1.4
  web-vitals: ^5.1.0
catalogs:
  cli:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.0.1
    bumpp: ^10.2.3
    eslint: ^9.36.0
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
    tsdown: ^0.15.4
    tsx: ^4.20.5
    typescript: ^5.9.2
    vite: ^7.1.7
  inlined:
    '@antfu/utils': ^9.2.1
  testing:
    tinyexec: ^1.0.1
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.5.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
